package interfazcarro;

import gnu.io.CommPortIdentifier;
import gnu.io.SerialPort;
import java.awt.Image;
import java.awt.Toolkit;
import static java.awt.image.ImageObserver.ERROR;
import java.io.OutputStream;
import java.util.Enumeration;
import javax.swing.JOptionPane;

/**
 *
 * @author jesusgabriel
 */
public class Interfaz extends javax.swing.JFrame {
    private static final String automatico = "5";
    private static final String detener = "0";
    private static final String adelante = "1";
    private static final String adelanteIzquierda = "7";
    private static final String adelanteDerecha = "6";
    private static final String atras = "2";
    private static final String pitar = "8";
    private static final String nopitar = "9";
    
    private OutputStream salida = null;
    SerialPort puertoSerial;
    private final String puerto = "COM8";    // al vincular el pc y el hc-06
    private static final int tiempo_espera = 2000; // milisegundos
    private static final int data_rate = 9600; // igual que en arduino
    
    
    public Interfaz() {
        initComponents();
        inicializarConexion();
        this.setTitle("CONTROL DEL CARRO"); //titulo del jframe
        this.setLocationRelativeTo(this); //centrar
        //this.setResizable(false); // no redimencionar
        this.setExtendedState(MAXIMIZED_BOTH); //en toda la pantalla
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/carro.png"));
        this.setIconImage(icono);
    }
    
    public void inicializarConexion(){
        CommPortIdentifier puertoID = null;
        Enumeration puertoEnum = CommPortIdentifier.getPortIdentifiers();
        while (puertoEnum.hasMoreElements()){
            CommPortIdentifier actualPuertoID = (CommPortIdentifier) puertoEnum.nextElement();
            if (puerto.equals(actualPuertoID.getName())){
                puertoID = actualPuertoID;
                break;
            }
        }
        if (puertoID==null){
            mostrarError ("No hay conexión");
            System.exit(ERROR);
        }
        try {
            puertoSerial = (SerialPort) puertoID.open(this.getClass().getName(),tiempo_espera);
            puertoSerial.setSerialPortParams (data_rate, SerialPort.DATABITS_8, SerialPort.STOPBITS_1, SerialPort.PARITY_NONE);
            salida = puertoSerial.getOutputStream();
        } catch (Exception e) {
            mostrarError (e.getMessage());
            System.exit(ERROR);
        }
  }
    public void mostrarError(String mensaje){
        JOptionPane.showConfirmDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }
    private void enviarDatos (String datos){
        try {
            salida.write(datos.getBytes());
        } catch (Exception e) {
            mostrarError ("Error");
            System.exit(ERROR);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBautomatico = new javax.swing.JButton();
        jBadelanteIzquierda = new javax.swing.JButton();
        jBadelante = new javax.swing.JButton();
        jBadelanteDerecha = new javax.swing.JButton();
        jBdetener = new javax.swing.JButton();
        jBatras = new javax.swing.JButton();
        jBapagarLuz = new javax.swing.JButton();
        jBencenderLuz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONTROL DEL CARRO");

        jBautomatico.setText("automatico");
        jBautomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBautomaticoActionPerformed(evt);
            }
        });

        jBadelanteIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Izquierda.png"))); // NOI18N
        jBadelanteIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBadelanteIzquierdaActionPerformed(evt);
            }
        });

        jBadelante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/adelante.png"))); // NOI18N
        jBadelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBadelanteActionPerformed(evt);
            }
        });

        jBadelanteDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Derecha.png"))); // NOI18N
        jBadelanteDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBadelanteDerechaActionPerformed(evt);
            }
        });

        jBdetener.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pare.png"))); // NOI18N
        jBdetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdetenerActionPerformed(evt);
            }
        });

        jBatras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        jBatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBatrasActionPerformed(evt);
            }
        });

        jBapagarLuz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/apagarLuz.png"))); // NOI18N
        jBapagarLuz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBapagarLuzActionPerformed(evt);
            }
        });

        jBencenderLuz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/encenderLuz.jpg"))); // NOI18N
        jBencenderLuz.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBencenderLuz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBencenderLuzActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jBadelante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(235, 235, 235))
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jBadelanteIzquierda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBdetener, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBadelanteDerecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(133, 133, 133))
            .addGroup(layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jBatras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(235, 235, 235))
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jBapagarLuz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(38, 38, 38)
                .addComponent(jBencenderLuz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(175, 175, 175))
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jBautomatico, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jBautomatico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jBadelante, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jBdetener, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBadelanteDerecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBadelanteIzquierda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(11, 11, 11)
                .addComponent(jBatras, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBapagarLuz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBencenderLuz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBatrasActionPerformed
        enviarDatos(atras);
    }//GEN-LAST:event_jBatrasActionPerformed

    private void jBautomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBautomaticoActionPerformed
        enviarDatos(automatico);
    }//GEN-LAST:event_jBautomaticoActionPerformed

    private void jBadelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBadelanteActionPerformed
        enviarDatos(adelante);
    }//GEN-LAST:event_jBadelanteActionPerformed

    private void jBadelanteIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBadelanteIzquierdaActionPerformed
        enviarDatos(adelanteIzquierda);
    }//GEN-LAST:event_jBadelanteIzquierdaActionPerformed

    private void jBadelanteDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBadelanteDerechaActionPerformed
        enviarDatos(adelanteDerecha);
    }//GEN-LAST:event_jBadelanteDerechaActionPerformed

    private void jBdetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdetenerActionPerformed
        enviarDatos(detener);
    }//GEN-LAST:event_jBdetenerActionPerformed

    private void jBapagarLuzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBapagarLuzActionPerformed
        enviarDatos(nopitar);
    }//GEN-LAST:event_jBapagarLuzActionPerformed

    private void jBencenderLuzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBencenderLuzActionPerformed
       enviarDatos(pitar);
    }//GEN-LAST:event_jBencenderLuzActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBadelante;
    private javax.swing.JButton jBadelanteDerecha;
    private javax.swing.JButton jBadelanteIzquierda;
    private javax.swing.JButton jBapagarLuz;
    private javax.swing.JButton jBatras;
    private javax.swing.JButton jBautomatico;
    private javax.swing.JButton jBdetener;
    private javax.swing.JButton jBencenderLuz;
    // End of variables declaration//GEN-END:variables
}
